### ISSUE TITLE
HW 1 Errors

### ISSUE THREAD

**Issue by NicholasAsirvadam** [alexvoobin/IDS2024S#2]
Hello, the following are errors I have found in your first homework assignment:
1. The link you have included to the course webpage does not work.
2. The formatted Thomas Edison quote is missing at the bottom of the page.

Since this is the first assignment, you have the opportunity to earn some points back on these mistakes if you resolve these issues by the start of class on Monday.

**Comment by alexvoobin** [comment]
Hello, so there is an issue that happened with my website link when I was trying to fix it and now I can't add my webpage course link back, I fixed the Thomas Edison quote, my website link got deleted.

**Comment by alexvoobin** [comment]
okay I think I have resolved it!! so will I get points added back to my hw if everything is correct??

**Comment by NicholasAsirvadam** [comment]
Yes, I am adding some points back to your grade!
